import '@scss/vuexy/scss/core.scss';
import '@scss/vuexy/scss/core-dark.scss';
import '@scss/vuexy/scss/theme-default.scss';
import '@scss/vuexy/scss/theme-default-dark.scss';
import '@scss/vuexy/scss/theme-semi-dark.scss';
import '@scss/vuexy/scss/theme-semi-dark-dark.scss';
import '@scss/vuexy/scss/theme-bordered.scss';
import '@scss/vuexy/scss/theme-bordered-dark.scss';
import '@scss/libs.scss';